### ISSUE TITLE
Issues running latest version

### ISSUE THREAD

**Issue by jonringer** [samueldr/nix-review-tools#5]
now when i try to run it, i just get:
```
08:54:20] jon@jon-desktop /home/jon/projects/nix-review-tools/tmp (master)
$ ../eval-report 1570790 > index.html
Traceback (most recent call last):
	7: from -e:1:in `<main>'
	6: from -e:1:in `load'
	5: from /home/jon/projects/nix-review-tools/eval-report:3:in `<top (required)>'
	4: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	3: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	2: from /home/jon/projects/nix-review-tools/lib/hydra.rb:12:in `<top (required)>'
	1: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- active_support (LoadError)
	30: from -e:1:in `<main>'
	29: from -e:1:in `load'
	28: from /home/jon/projects/nix-review-tools/eval-report:3:in `<top (required)>'
	27: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	26: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	25: from /home/jon/projects/nix-review-tools/lib/hydra.rb:12:in `<top (required)>'
	24: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	23: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
	22: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:168:in `require'
	21: from /nix/store/9cb55j9v6l95wklsiascn8bg99gvgykl-ruby2.6.5-activesupport-6.0.2.1/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support.rb:27:in `<top (required)>'
	20: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	19: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	18: from /nix/store/hb8q5xpqk3i5hcg969vfxg31gyrcmrkb-review-tools-dependencies/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/dependencies/autoload.rb:3:in `<top (required)>'
	17: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	16: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	15: from /nix/store/hb8q5xpqk3i5hcg969vfxg31gyrcmrkb-review-tools-dependencies/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/inflector/methods.rb:3:in `<top (required)>'
	14: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	13: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	12: from /nix/store/hb8q5xpqk3i5hcg969vfxg31gyrcmrkb-review-tools-dependencies/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/inflections.rb:3:in `<top (required)>'
	11: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	10: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 9: from /nix/store/hb8q5xpqk3i5hcg969vfxg31gyrcmrkb-review-tools-dependencies/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/inflector/inflections.rb:4:in `<top (required)>'
	 8: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 7: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 6: from /nix/store/hb8q5xpqk3i5hcg969vfxg31gyrcmrkb-review-tools-dependencies/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.1/lib/active_support/i18n.rb:15:in `<top (required)>'
	 5: from /nix/store/hb8q5xpqk3i5hcg969vfxg31gyrcmrkb-review-tools-dependencies/lib/ruby/gems/2.6.0/gems/i18n-1.8.2/lib/i18n.rb:55:in `load_path'
	 4: from /nix/store/hb8q5xpqk3i5hcg969vfxg31gyrcmrkb-review-tools-dependencies/lib/ruby/gems/2.6.0/gems/i18n-1.8.2/lib/i18n.rb:42:in `config'
	 3: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 2: from /nix/store/12a7h4w68f96j56kzwxxpxbc4zq7n76p-ruby-2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	 1: from /nix/store/hb8q5xpqk3i5hcg969vfxg31gyrcmrkb-review-tools-dependencies/lib/ruby/gems/2.6.0/gems/i18n-1.8.2/lib/i18n/config.rb:5:in `<top (required)>'
/nix/store/hb8q5xpqk3i5hcg969vfxg31gyrcmrkb-review-tools-dependencies/lib/ruby/gems/2.6.0/gems/i18n-1.8.2/lib/i18n/config.rb:6:in `<module:I18n>': uninitialized constant I18n::Config (NameError)
```

**Comment by samueldr** [comment]
I was able to reproduce using:

```
export NIX_PATH=nixpkgs=channel:nixos-unstable
```

Uh...
